<a href="https://colab.research.google.com/github/kwankao26/229352-Course-Name-Statistical-Learning-for-Data-Science-2-Semester-1-2025/blob/Lab/660510753_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [2]:
a = torch.tensor(8)
b = torch.tensor(9)
print(a)
print(b)
print(a+b)

tensor(8)
tensor(9)
tensor(17)


### Convert a tensor to scalar

In [3]:
a.item()

8

### Creating 2D tensor

In [4]:
A = torch.tensor([[1, 2], [3, 4]])
print(A)

tensor([[1, 2],
        [3, 4]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [5]:
A.numpy()

array([[1, 2],
       [3, 4]])

### Convert from numpy array to tensor

In [6]:
B = np.array([[1, 2], [3, 4]])

C = torch.from_numpy(B)
print(C)

tensor([[1, 2],
        [3, 4]])


## Basic operations

In [7]:
D = 2*C

E = C - 10

print(D)
print(E)

tensor([[2, 4],
        [6, 8]])
tensor([[-9, -8],
        [-7, -6]])


### Matrix multiplication

In [8]:
print(torch.matmul(D, E))
print(torch.mm(D, E))
print(D @ E)

tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])


### Matrix transpose

In [9]:
print(C)
print( C.t() )

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


## Creating a specific type of tensor

In [10]:
# print(torch.zeros(2,3))
# print(torch.ones(2,3))
# print(torch.rand(2,3))
# print(torch.randn(2,3))  # sample each number from N(0, 1)
# print(torch.arange(9))

## Tensor's shape

### Checking the shape of a tensor

In [11]:
F = torch.zeros((4, 5))
print(F.shape)
print(F.size())

torch.Size([4, 5])
torch.Size([4, 5])


### Changing the shape of a tensor

In [12]:
G = torch.arange(6)
print(G.view(2, 3))
print(G.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [13]:
G1 = G.reshape(2, 3)
G1

tensor([[0, 1, 2],
        [3, 4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

In [14]:
G2 = G.view(2, 3)
G2

tensor([[0, 1, 2],
        [3, 4, 5]])

In [15]:
G = torch.arange(6)
print(G.view(2, 3))
print(G.reshape(2, 3))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


### Stacking and concatenating tensors

In [16]:
H = torch.arange(6)
I = torch.stack([H, H, H, H], axis=0)
J = torch.stack([H, H, H, H], axis=1)
print(I)
print(J)

tensor([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]])
tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5]])


In [17]:
# concatenate

I = torch.cat([H, H, H, H], axis=0)
print(I)
# J = torch.cat([H, H, H, H], axis=1)
#print(J)

tensor([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])


### Squeezing a tensor (removing an extra dimension)

In [18]:
# [[1,2]] this is (1,2) tensor, want (2,)
print("H=", H) # shape = (6,)
K = H.reshape(1,6)
print("K=", K)
print(K.shape)

H= tensor([0, 1, 2, 3, 4, 5])
K= tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])


In [19]:
print(K.squeeze())

tensor([0, 1, 2, 3, 4, 5])


In [20]:
# H.shape = (6, )
L = H.unsqueeze(axis=0)  # L.shape(1, 6)
M = H.unsqueeze(axis=1)  # L.shape(6, 1)
print(L)
print(M)

tensor([[0, 1, 2, 3, 4, 5]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])


## Indexing

In [21]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


## PyTorch and GPU

check if GPU is available

In [22]:
torch.cuda.is_available()

True

In [23]:
Q = torch.tensor([1, 2, 3])
print(Q.device)

cpu


In [24]:
R = Q.to('cuda')
print(Q.device)
print(R.device)

cpu
cuda:0


In [25]:
R.cpu().numpy()

array([1, 2, 3])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [43]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [44]:
#1
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

print(X.shape)
print(b.shape)
print(e.shape)

torch.Size([200, 7])
torch.Size([8, 1])
torch.Size([200, 1])


In [45]:
#2
ones = torch.ones(200, 1)
print(ones.shape)

torch.Size([200, 1])


In [46]:
#3
X = torch.cat([ones, X], dim=1)
print(X)


tensor([[ 1.0000,  2.5906, -0.1442,  ...,  0.3704,  1.0243,  0.3509],
        [ 1.0000, -0.1160, -0.5129,  ...,  0.8523,  0.3443, -0.2194],
        [ 1.0000,  1.6952,  0.7313,  ...,  0.9143, -1.2950,  0.9506],
        ...,
        [ 1.0000, -0.1819, -0.7622,  ...,  2.3914, -1.2396, -0.0733],
        [ 1.0000,  0.0529,  0.9842,  ..., -0.6918,  0.6105,  0.5743],
        [ 1.0000,  0.0542,  0.1354,  ...,  1.0258,  0.5135,  0.7213]])


In [48]:
#4
y = X @ b + e
print(y)

tensor([[ 0.1709],
        [ 1.2905],
        [-3.8014],
        [-2.9848],
        [-1.8588],
        [-3.4213],
        [ 0.5205],
        [-1.9539],
        [-3.0830],
        [ 5.9926],
        [ 2.1340],
        [-1.2139],
        [-2.1837],
        [ 4.2594],
        [-2.1842],
        [-1.5498],
        [-3.5498],
        [-1.4226],
        [-1.5471],
        [-1.9985],
        [-1.2902],
        [-1.5186],
        [ 3.7983],
        [-1.5178],
        [-0.6752],
        [-4.1522],
        [-1.3738],
        [ 0.7177],
        [-0.2385],
        [-0.1289],
        [ 1.0513],
        [-0.0340],
        [ 1.2910],
        [ 0.2476],
        [ 0.7186],
        [-2.9613],
        [ 4.6583],
        [ 0.6427],
        [-0.4228],
        [ 1.3792],
        [ 0.1927],
        [-4.0754],
        [ 0.2504],
        [-7.6184],
        [-1.2870],
        [-1.6575],
        [ 3.4576],
        [-0.1835],
        [-2.7680],
        [-2.4057],
        [-1.6278],
        [-1.3031],
        [-4.

In [52]:
#5
XT_X = X.T @ X
XT_X_inv = torch.inverse(XT_X)
b_hat = XT_X_inv @ X.T @ y
print(b_hat)


tensor([[-0.3584],
        [-0.3855],
        [-1.3543],
        [ 0.1302],
        [ 0.5462],
        [-0.0097],
        [ 1.3970],
        [ 0.1155]])


In [59]:
#6
y_hat = X @ b_hat
print(y_hat)


tensor([[ 0.1188],
        [ 2.3704],
        [-2.9777],
        [-3.6560],
        [-2.4237],
        [-3.3273],
        [ 0.0227],
        [-1.3787],
        [-2.2046],
        [ 5.7670],
        [ 1.2439],
        [-0.8976],
        [-2.5558],
        [ 1.9745],
        [-1.3190],
        [-1.4843],
        [-3.3794],
        [-0.6141],
        [-3.4155],
        [-2.4463],
        [-1.0471],
        [-0.1944],
        [ 2.9633],
        [-2.1133],
        [-1.0347],
        [-2.5003],
        [-1.3806],
        [ 0.6772],
        [ 0.0655],
        [ 0.7069],
        [ 0.9104],
        [ 0.0129],
        [ 0.5202],
        [ 1.9759],
        [-0.0441],
        [-4.2609],
        [ 2.8334],
        [-0.3127],
        [-0.9587],
        [ 0.3649],
        [ 2.4088],
        [-0.6362],
        [ 0.2573],
        [-4.5167],
        [-1.0936],
        [-3.2769],
        [ 3.9117],
        [-0.5069],
        [-3.4169],
        [-2.7120],
        [-1.9562],
        [-1.3698],
        [-3.

In [56]:
#7
y_np = y.numpy()
y_hat_np = y_hat.detach().numpy()

MSE = np.mean((y_np - y_hat_np) ** 2)
print("MSE:", MSE)

MSE: 1.0731604
